### PR TITLE
Brushing up types

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
- exporting missing types
- integrating types into Types.hs

### CODE REVIEW

**Review by khibino — COMMENTED** [review]
@kazu-yamamoto
Forgot to add src/DNSC/Types.hs?

**Comment by kazu-yamamoto** [comment]
My bad. I added it.

**Review by khibino — COMMENTED** [review]
When importing `DNSC.Types`, would explict import list or qualified import be better?

**Comment by kazu-yamamoto** [comment]
`Types` is like prelude. So, I suggest just import it (non explicit, non qualified).

**Comment by kazu-yamamoto** [comment]
If you really want to choose one among the two, I would suggest *explicit*.

**Review by khibino — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Would you like to merge this by yourself?

**Comment by kazu-yamamoto** [comment]
Should we also export `Ranking_(..)`?

**Comment by khibino** [comment]
Not considered necessary because of no pattern match

**Pull request merged**
